/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "espfm.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(FanInfo, FanInfo, AUTO)


PB_BIND(SourceInfo, SourceInfo, AUTO)


PB_BIND(CurvePoint, CurvePoint, AUTO)


PB_BIND(CurveInfo, CurveInfo, AUTO)


PB_BIND(ScheduleInfo, ScheduleInfo, AUTO)


PB_BIND(WifiApRecord, WifiApRecord, AUTO)


PB_BIND(SystemInfo, SystemInfo, AUTO)


PB_BIND(WifiStatus, WifiStatus, AUTO)


PB_BIND(FanList, FanList, 2)


PB_BIND(FanCreateRequest, FanCreateRequest, AUTO)


PB_BIND(FanUpdateRequest, FanUpdateRequest, AUTO)


PB_BIND(FanId, FanId, AUTO)


PB_BIND(SourceList, SourceList, 2)


PB_BIND(SourceCreateRequest, SourceCreateRequest, AUTO)


PB_BIND(SourceUpdateRequest, SourceUpdateRequest, AUTO)


PB_BIND(ManualTempRequest, ManualTempRequest, AUTO)


PB_BIND(Ds18b20Device, Ds18b20Device, AUTO)


PB_BIND(Ds18b20ScanResponse, Ds18b20ScanResponse, AUTO)


PB_BIND(Ds18b20ConfigRequest, Ds18b20ConfigRequest, AUTO)


PB_BIND(CurveList, CurveList, 2)


PB_BIND(CurveCreateRequest, CurveCreateRequest, AUTO)


PB_BIND(CurveUpdateRequest, CurveUpdateRequest, AUTO)


PB_BIND(ScheduleList, ScheduleList, AUTO)


PB_BIND(ScheduleCreateRequest, ScheduleCreateRequest, AUTO)


PB_BIND(ScheduleUpdateRequest, ScheduleUpdateRequest, AUTO)


PB_BIND(WifiScanResult, WifiScanResult, 2)


PB_BIND(WifiConnectRequest, WifiConnectRequest, AUTO)


PB_BIND(HostnameRequest, HostnameRequest, AUTO)


PB_BIND(ConfigFile, ConfigFile, 2)


PB_BIND(Empty, Empty, AUTO)


PB_BIND(StatusResponse, StatusResponse, AUTO)











