/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_ESPFM_PB_H_INCLUDED
#define PB_ESPFM_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _FanMode {
    FanMode_FAN_MODE_MANUAL = 0,
    FanMode_FAN_MODE_AUTO = 1
} FanMode;

typedef enum _SourceType {
    SourceType_SOURCE_TYPE_NTC = 0,
    SourceType_SOURCE_TYPE_DS18B20 = 1,
    SourceType_SOURCE_TYPE_MANUAL = 2
} SourceType;

typedef enum _SourceStatus {
    SourceStatus_SOURCE_STATUS_VALID = 0,
    SourceStatus_SOURCE_STATUS_STALE = 1,
    SourceStatus_SOURCE_STATUS_INVALID = 2
} SourceStatus;

typedef enum _FanAlarm {
    FanAlarm_FAN_ALARM_NONE = 0,
    FanAlarm_FAN_ALARM_STALL = 1,
    FanAlarm_FAN_ALARM_OVERTEMP = 2
} FanAlarm;

/* Struct definitions */
typedef struct _FanInfo {
    uint32_t id;
    char name[16]; /* max 15 chars */
    FanMode mode;
    uint32_t duty; /* 0-100% */
    uint32_t rpm;
    bool enabled;
    bool inverted;
    uint32_t pwm_gpio;
    uint32_t tach_gpio; /* 255=none */
    uint32_t source_id; /* 255=none */
    uint32_t curve_id; /* 255=none */
    uint32_t schedule_id; /* 255=none */
    uint32_t group_id;
    FanAlarm alarm;
} FanInfo;

typedef struct _SourceInfo {
    uint32_t id;
    char name[16];
    SourceType type;
    SourceStatus status;
    float temp_c;
    uint32_t gpio; /* 255=none */
    uint64_t ds18b20_rom_code;
} SourceInfo;

typedef struct _CurvePoint {
    float temp_c;
    uint32_t duty; /* 0-100% */
} CurvePoint;

typedef struct _CurveInfo {
    uint32_t id;
    char name[16];
    pb_size_t points_count;
    CurvePoint points[10]; /* 2-10 points */
} CurveInfo;

typedef struct _ScheduleInfo {
    uint32_t id;
    uint32_t fan_id;
    uint32_t duty; /* 0-100% */
    uint32_t start_min; /* 0-1439 minutes since midnight */
    uint32_t end_min;
    bool enabled;
    char name[16]; /* optional display name */
} ScheduleInfo;

typedef struct _WifiApRecord {
    char ssid[33];
    int32_t rssi;
    uint32_t channel;
    uint32_t authmode;
} WifiApRecord;

typedef struct _SystemInfo {
    char version[12];
    uint32_t uptime_s;
    uint32_t heap_free;
    uint32_t fan_count;
    uint32_t source_count;
    uint32_t curve_count;
    uint32_t schedule_count;
    char hostname[64]; /* mDNS hostname (without .local) */
} SystemInfo;

typedef struct _WifiStatus {
    bool sta_connected;
    char sta_ip[16];
    char ap_ip[16];
} WifiStatus;

typedef struct _FanList {
    pb_size_t fans_count;
    FanInfo fans[8];
} FanList;

typedef struct _FanCreateRequest {
    uint32_t pwm_gpio;
    uint32_t tach_gpio; /* optional, 255=none */
    char name[16];
} FanCreateRequest;

typedef struct _FanUpdateRequest {
    uint32_t id; /* required */
    bool has_mode;
    FanMode mode;
    bool has_duty;
    uint32_t duty;
    bool has_source_id;
    uint32_t source_id;
    bool has_curve_id;
    uint32_t curve_id;
    bool has_schedule_id;
    uint32_t schedule_id;
    bool has_group_id;
    uint32_t group_id;
    bool has_inverted;
    bool inverted;
    bool has_enabled;
    bool enabled;
    bool has_pwm_gpio;
    uint32_t pwm_gpio; /* NEW */
    bool has_tach_gpio;
    uint32_t tach_gpio; /* NEW (255=none) */
    bool has_name;
    char name[16]; /* rename fan */
} FanUpdateRequest;

typedef struct _FanId {
    uint32_t id;
} FanId;

typedef struct _SourceList {
    pb_size_t sources_count;
    SourceInfo sources[8];
} SourceList;

typedef struct _SourceCreateRequest {
    SourceType type;
    char name[16];
    uint32_t gpio; /* optional, 255=none */
    uint64_t ds18b20_rom_code;
} SourceCreateRequest;

typedef struct _SourceUpdateRequest {
    uint32_t id;
    char name[16];
} SourceUpdateRequest;

typedef struct _ManualTempRequest {
    uint32_t id;
    float temp_c;
} ManualTempRequest;

typedef struct _Ds18b20Device {
    uint32_t index;
    uint64_t rom_code;
    float temp_c;
} Ds18b20Device;

typedef struct _Ds18b20ScanResponse {
    pb_callback_t devices;
    uint32_t device_count;
} Ds18b20ScanResponse;

typedef struct _Ds18b20ConfigRequest {
    uint32_t gpio;
} Ds18b20ConfigRequest;

typedef struct _CurveList {
    pb_size_t curves_count;
    CurveInfo curves[16];
} CurveList;

typedef struct _CurveCreateRequest {
    char name[16];
    pb_size_t points_count;
    CurvePoint points[10];
} CurveCreateRequest;

typedef struct _CurveUpdateRequest {
    uint32_t id;
    char name[16];
    pb_size_t points_count;
    CurvePoint points[10];
} CurveUpdateRequest;

typedef struct _ScheduleList {
    pb_size_t schedules_count;
    ScheduleInfo schedules[8];
} ScheduleList;

typedef struct _ScheduleCreateRequest {
    uint32_t fan_id;
    uint32_t duty;
    uint32_t start_min;
    uint32_t end_min;
    bool enabled;
    char name[16]; /* optional display name */
} ScheduleCreateRequest;

typedef struct _ScheduleUpdateRequest {
    uint32_t id;
    bool has_fan_id;
    uint32_t fan_id;
    bool has_duty;
    uint32_t duty;
    bool has_start_min;
    uint32_t start_min;
    bool has_end_min;
    uint32_t end_min;
    bool has_enabled;
    bool enabled;
    bool has_name;
    char name[16]; /* rename schedule */
} ScheduleUpdateRequest;

typedef struct _WifiScanResult {
    pb_size_t aps_count;
    WifiApRecord aps[16];
} WifiScanResult;

typedef struct _WifiConnectRequest {
    char ssid[33];
    char password[64];
} WifiConnectRequest;

typedef struct _HostnameRequest {
    char hostname[64]; /* new hostname to set */
} HostnameRequest;

typedef struct _ConfigFile {
    char version[8]; /* "3.0" */
    bool has_fans;
    FanList fans;
    bool has_sources;
    SourceList sources;
    bool has_curves;
    CurveList curves;
    bool has_schedules;
    ScheduleList schedules;
} ConfigFile;

typedef struct _Empty {
    char dummy_field;
} Empty;

typedef struct _StatusResponse {
    bool ok;
    uint32_t error_code; /* 0 on success */
    char error_msg[64]; /* empty on success */
} StatusResponse;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _FanMode_MIN FanMode_FAN_MODE_MANUAL
#define _FanMode_MAX FanMode_FAN_MODE_AUTO
#define _FanMode_ARRAYSIZE ((FanMode)(FanMode_FAN_MODE_AUTO+1))

#define _SourceType_MIN SourceType_SOURCE_TYPE_NTC
#define _SourceType_MAX SourceType_SOURCE_TYPE_MANUAL
#define _SourceType_ARRAYSIZE ((SourceType)(SourceType_SOURCE_TYPE_MANUAL+1))

#define _SourceStatus_MIN SourceStatus_SOURCE_STATUS_VALID
#define _SourceStatus_MAX SourceStatus_SOURCE_STATUS_INVALID
#define _SourceStatus_ARRAYSIZE ((SourceStatus)(SourceStatus_SOURCE_STATUS_INVALID+1))

#define _FanAlarm_MIN FanAlarm_FAN_ALARM_NONE
#define _FanAlarm_MAX FanAlarm_FAN_ALARM_OVERTEMP
#define _FanAlarm_ARRAYSIZE ((FanAlarm)(FanAlarm_FAN_ALARM_OVERTEMP+1))

#define FanInfo_mode_ENUMTYPE FanMode
#define FanInfo_alarm_ENUMTYPE FanAlarm

#define SourceInfo_type_ENUMTYPE SourceType
#define SourceInfo_status_ENUMTYPE SourceStatus









#define FanUpdateRequest_mode_ENUMTYPE FanMode



#define SourceCreateRequest_type_ENUMTYPE SourceType



















/* Initializer values for message structs */
#define FanInfo_init_default                     {0, "", _FanMode_MIN, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, _FanAlarm_MIN}
#define SourceInfo_init_default                  {0, "", _SourceType_MIN, _SourceStatus_MIN, 0, 0, 0}
#define CurvePoint_init_default                  {0, 0}
#define CurveInfo_init_default                   {0, "", 0, {CurvePoint_init_default, CurvePoint_init_default, CurvePoint_init_default, CurvePoint_init_default, CurvePoint_init_default, CurvePoint_init_default, CurvePoint_init_default, CurvePoint_init_default, CurvePoint_init_default, CurvePoint_init_default}}
#define ScheduleInfo_init_default                {0, 0, 0, 0, 0, 0, ""}
#define WifiApRecord_init_default                {"", 0, 0, 0}
#define SystemInfo_init_default                  {"", 0, 0, 0, 0, 0, 0, ""}
#define WifiStatus_init_default                  {0, "", ""}
#define FanList_init_default                     {0, {FanInfo_init_default, FanInfo_init_default, FanInfo_init_default, FanInfo_init_default, FanInfo_init_default, FanInfo_init_default, FanInfo_init_default, FanInfo_init_default}}
#define FanCreateRequest_init_default            {0, 0, ""}
#define FanUpdateRequest_init_default            {0, false, _FanMode_MIN, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, ""}
#define FanId_init_default                       {0}
#define SourceList_init_default                  {0, {SourceInfo_init_default, SourceInfo_init_default, SourceInfo_init_default, SourceInfo_init_default, SourceInfo_init_default, SourceInfo_init_default, SourceInfo_init_default, SourceInfo_init_default}}
#define SourceCreateRequest_init_default         {_SourceType_MIN, "", 0, 0}
#define SourceUpdateRequest_init_default         {0, ""}
#define ManualTempRequest_init_default           {0, 0}
#define Ds18b20Device_init_default               {0, 0, 0}
#define Ds18b20ScanResponse_init_default         {{{NULL}, NULL}, 0}
#define Ds18b20ConfigRequest_init_default        {0}
#define CurveList_init_default                   {0, {CurveInfo_init_default, CurveInfo_init_default, CurveInfo_init_default, CurveInfo_init_default, CurveInfo_init_default, CurveInfo_init_default, CurveInfo_init_default, CurveInfo_init_default, CurveInfo_init_default, CurveInfo_init_default, CurveInfo_init_default, CurveInfo_init_default, CurveInfo_init_default, CurveInfo_init_default, CurveInfo_init_default, CurveInfo_init_default}}
#define CurveCreateRequest_init_default          {"", 0, {CurvePoint_init_default, CurvePoint_init_default, CurvePoint_init_default, CurvePoint_init_default, CurvePoint_init_default, CurvePoint_init_default, CurvePoint_init_default, CurvePoint_init_default, CurvePoint_init_default, CurvePoint_init_default}}
#define CurveUpdateRequest_init_default          {0, "", 0, {CurvePoint_init_default, CurvePoint_init_default, CurvePoint_init_default, CurvePoint_init_default, CurvePoint_init_default, CurvePoint_init_default, CurvePoint_init_default, CurvePoint_init_default, CurvePoint_init_default, CurvePoint_init_default}}
#define ScheduleList_init_default                {0, {ScheduleInfo_init_default, ScheduleInfo_init_default, ScheduleInfo_init_default, ScheduleInfo_init_default, ScheduleInfo_init_default, ScheduleInfo_init_default, ScheduleInfo_init_default, ScheduleInfo_init_default}}
#define ScheduleCreateRequest_init_default       {0, 0, 0, 0, 0, ""}
#define ScheduleUpdateRequest_init_default       {0, false, 0, false, 0, false, 0, false, 0, false, 0, false, ""}
#define WifiScanResult_init_default              {0, {WifiApRecord_init_default, WifiApRecord_init_default, WifiApRecord_init_default, WifiApRecord_init_default, WifiApRecord_init_default, WifiApRecord_init_default, WifiApRecord_init_default, WifiApRecord_init_default, WifiApRecord_init_default, WifiApRecord_init_default, WifiApRecord_init_default, WifiApRecord_init_default, WifiApRecord_init_default, WifiApRecord_init_default, WifiApRecord_init_default, WifiApRecord_init_default}}
#define WifiConnectRequest_init_default          {"", ""}
#define HostnameRequest_init_default             {""}
#define ConfigFile_init_default                  {"", false, FanList_init_default, false, SourceList_init_default, false, CurveList_init_default, false, ScheduleList_init_default}
#define Empty_init_default                       {0}
#define StatusResponse_init_default              {0, 0, ""}
#define FanInfo_init_zero                        {0, "", _FanMode_MIN, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, _FanAlarm_MIN}
#define SourceInfo_init_zero                     {0, "", _SourceType_MIN, _SourceStatus_MIN, 0, 0, 0}
#define CurvePoint_init_zero                     {0, 0}
#define CurveInfo_init_zero                      {0, "", 0, {CurvePoint_init_zero, CurvePoint_init_zero, CurvePoint_init_zero, CurvePoint_init_zero, CurvePoint_init_zero, CurvePoint_init_zero, CurvePoint_init_zero, CurvePoint_init_zero, CurvePoint_init_zero, CurvePoint_init_zero}}
#define ScheduleInfo_init_zero                   {0, 0, 0, 0, 0, 0, ""}
#define WifiApRecord_init_zero                   {"", 0, 0, 0}
#define SystemInfo_init_zero                     {"", 0, 0, 0, 0, 0, 0, ""}
#define WifiStatus_init_zero                     {0, "", ""}
#define FanList_init_zero                        {0, {FanInfo_init_zero, FanInfo_init_zero, FanInfo_init_zero, FanInfo_init_zero, FanInfo_init_zero, FanInfo_init_zero, FanInfo_init_zero, FanInfo_init_zero}}
#define FanCreateRequest_init_zero               {0, 0, ""}
#define FanUpdateRequest_init_zero               {0, false, _FanMode_MIN, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, ""}
#define FanId_init_zero                          {0}
#define SourceList_init_zero                     {0, {SourceInfo_init_zero, SourceInfo_init_zero, SourceInfo_init_zero, SourceInfo_init_zero, SourceInfo_init_zero, SourceInfo_init_zero, SourceInfo_init_zero, SourceInfo_init_zero}}
#define SourceCreateRequest_init_zero            {_SourceType_MIN, "", 0, 0}
#define SourceUpdateRequest_init_zero            {0, ""}
#define ManualTempRequest_init_zero              {0, 0}
#define Ds18b20Device_init_zero                  {0, 0, 0}
#define Ds18b20ScanResponse_init_zero            {{{NULL}, NULL}, 0}
#define Ds18b20ConfigRequest_init_zero           {0}
#define CurveList_init_zero                      {0, {CurveInfo_init_zero, CurveInfo_init_zero, CurveInfo_init_zero, CurveInfo_init_zero, CurveInfo_init_zero, CurveInfo_init_zero, CurveInfo_init_zero, CurveInfo_init_zero, CurveInfo_init_zero, CurveInfo_init_zero, CurveInfo_init_zero, CurveInfo_init_zero, CurveInfo_init_zero, CurveInfo_init_zero, CurveInfo_init_zero, CurveInfo_init_zero}}
#define CurveCreateRequest_init_zero             {"", 0, {CurvePoint_init_zero, CurvePoint_init_zero, CurvePoint_init_zero, CurvePoint_init_zero, CurvePoint_init_zero, CurvePoint_init_zero, CurvePoint_init_zero, CurvePoint_init_zero, CurvePoint_init_zero, CurvePoint_init_zero}}
#define CurveUpdateRequest_init_zero             {0, "", 0, {CurvePoint_init_zero, CurvePoint_init_zero, CurvePoint_init_zero, CurvePoint_init_zero, CurvePoint_init_zero, CurvePoint_init_zero, CurvePoint_init_zero, CurvePoint_init_zero, CurvePoint_init_zero, CurvePoint_init_zero}}
#define ScheduleList_init_zero                   {0, {ScheduleInfo_init_zero, ScheduleInfo_init_zero, ScheduleInfo_init_zero, ScheduleInfo_init_zero, ScheduleInfo_init_zero, ScheduleInfo_init_zero, ScheduleInfo_init_zero, ScheduleInfo_init_zero}}
#define ScheduleCreateRequest_init_zero          {0, 0, 0, 0, 0, ""}
#define ScheduleUpdateRequest_init_zero          {0, false, 0, false, 0, false, 0, false, 0, false, 0, false, ""}
#define WifiScanResult_init_zero                 {0, {WifiApRecord_init_zero, WifiApRecord_init_zero, WifiApRecord_init_zero, WifiApRecord_init_zero, WifiApRecord_init_zero, WifiApRecord_init_zero, WifiApRecord_init_zero, WifiApRecord_init_zero, WifiApRecord_init_zero, WifiApRecord_init_zero, WifiApRecord_init_zero, WifiApRecord_init_zero, WifiApRecord_init_zero, WifiApRecord_init_zero, WifiApRecord_init_zero, WifiApRecord_init_zero}}
#define WifiConnectRequest_init_zero             {"", ""}
#define HostnameRequest_init_zero                {""}
#define ConfigFile_init_zero                     {"", false, FanList_init_zero, false, SourceList_init_zero, false, CurveList_init_zero, false, ScheduleList_init_zero}
#define Empty_init_zero                          {0}
#define StatusResponse_init_zero                 {0, 0, ""}

/* Field tags (for use in manual encoding/decoding) */
#define FanInfo_id_tag                           1
#define FanInfo_name_tag                         2
#define FanInfo_mode_tag                         3
#define FanInfo_duty_tag                         4
#define FanInfo_rpm_tag                          5
#define FanInfo_enabled_tag                      6
#define FanInfo_inverted_tag                     7
#define FanInfo_pwm_gpio_tag                     8
#define FanInfo_tach_gpio_tag                    9
#define FanInfo_source_id_tag                    10
#define FanInfo_curve_id_tag                     11
#define FanInfo_schedule_id_tag                  12
#define FanInfo_group_id_tag                     13
#define FanInfo_alarm_tag                        14
#define SourceInfo_id_tag                        1
#define SourceInfo_name_tag                      2
#define SourceInfo_type_tag                      3
#define SourceInfo_status_tag                    4
#define SourceInfo_temp_c_tag                    5
#define SourceInfo_gpio_tag                      6
#define SourceInfo_ds18b20_rom_code_tag          7
#define CurvePoint_temp_c_tag                    1
#define CurvePoint_duty_tag                      2
#define CurveInfo_id_tag                         1
#define CurveInfo_name_tag                       2
#define CurveInfo_points_tag                     3
#define ScheduleInfo_id_tag                      1
#define ScheduleInfo_fan_id_tag                  2
#define ScheduleInfo_duty_tag                    3
#define ScheduleInfo_start_min_tag               4
#define ScheduleInfo_end_min_tag                 5
#define ScheduleInfo_enabled_tag                 6
#define ScheduleInfo_name_tag                    7
#define WifiApRecord_ssid_tag                    1
#define WifiApRecord_rssi_tag                    2
#define WifiApRecord_channel_tag                 3
#define WifiApRecord_authmode_tag                4
#define SystemInfo_version_tag                   1
#define SystemInfo_uptime_s_tag                  2
#define SystemInfo_heap_free_tag                 3
#define SystemInfo_fan_count_tag                 4
#define SystemInfo_source_count_tag              5
#define SystemInfo_curve_count_tag               6
#define SystemInfo_schedule_count_tag            7
#define SystemInfo_hostname_tag                  8
#define WifiStatus_sta_connected_tag             1
#define WifiStatus_sta_ip_tag                    2
#define WifiStatus_ap_ip_tag                     3
#define FanList_fans_tag                         1
#define FanCreateRequest_pwm_gpio_tag            1
#define FanCreateRequest_tach_gpio_tag           2
#define FanCreateRequest_name_tag                3
#define FanUpdateRequest_id_tag                  1
#define FanUpdateRequest_mode_tag                2
#define FanUpdateRequest_duty_tag                3
#define FanUpdateRequest_source_id_tag           4
#define FanUpdateRequest_curve_id_tag            5
#define FanUpdateRequest_schedule_id_tag         6
#define FanUpdateRequest_group_id_tag            7
#define FanUpdateRequest_inverted_tag            8
#define FanUpdateRequest_enabled_tag             9
#define FanUpdateRequest_pwm_gpio_tag            10
#define FanUpdateRequest_tach_gpio_tag           11
#define FanUpdateRequest_name_tag                12
#define FanId_id_tag                             1
#define SourceList_sources_tag                   1
#define SourceCreateRequest_type_tag             1
#define SourceCreateRequest_name_tag             2
#define SourceCreateRequest_gpio_tag             3
#define SourceCreateRequest_ds18b20_rom_code_tag 4
#define SourceUpdateRequest_id_tag               1
#define SourceUpdateRequest_name_tag             2
#define ManualTempRequest_id_tag                 1
#define ManualTempRequest_temp_c_tag             2
#define Ds18b20Device_index_tag                  1
#define Ds18b20Device_rom_code_tag               2
#define Ds18b20Device_temp_c_tag                 3
#define Ds18b20ScanResponse_devices_tag          1
#define Ds18b20ScanResponse_device_count_tag     2
#define Ds18b20ConfigRequest_gpio_tag            1
#define CurveList_curves_tag                     1
#define CurveCreateRequest_name_tag              1
#define CurveCreateRequest_points_tag            2
#define CurveUpdateRequest_id_tag                1
#define CurveUpdateRequest_name_tag              2
#define CurveUpdateRequest_points_tag            3
#define ScheduleList_schedules_tag               1
#define ScheduleCreateRequest_fan_id_tag         1
#define ScheduleCreateRequest_duty_tag           2
#define ScheduleCreateRequest_start_min_tag      3
#define ScheduleCreateRequest_end_min_tag        4
#define ScheduleCreateRequest_enabled_tag        5
#define ScheduleCreateRequest_name_tag           6
#define ScheduleUpdateRequest_id_tag             1
#define ScheduleUpdateRequest_fan_id_tag         2
#define ScheduleUpdateRequest_duty_tag           3
#define ScheduleUpdateRequest_start_min_tag      4
#define ScheduleUpdateRequest_end_min_tag        5
#define ScheduleUpdateRequest_enabled_tag        6
#define ScheduleUpdateRequest_name_tag           7
#define WifiScanResult_aps_tag                   1
#define WifiConnectRequest_ssid_tag              1
#define WifiConnectRequest_password_tag          2
#define HostnameRequest_hostname_tag             1
#define ConfigFile_version_tag                   1
#define ConfigFile_fans_tag                      2
#define ConfigFile_sources_tag                   3
#define ConfigFile_curves_tag                    4
#define ConfigFile_schedules_tag                 5
#define StatusResponse_ok_tag                    1
#define StatusResponse_error_code_tag            2
#define StatusResponse_error_msg_tag             3

/* Struct field encoding specification for nanopb */
#define FanInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   id,                1) \
X(a, STATIC,   SINGULAR, STRING,   name,              2) \
X(a, STATIC,   SINGULAR, UENUM,    mode,              3) \
X(a, STATIC,   SINGULAR, UINT32,   duty,              4) \
X(a, STATIC,   SINGULAR, UINT32,   rpm,               5) \
X(a, STATIC,   SINGULAR, BOOL,     enabled,           6) \
X(a, STATIC,   SINGULAR, BOOL,     inverted,          7) \
X(a, STATIC,   SINGULAR, UINT32,   pwm_gpio,          8) \
X(a, STATIC,   SINGULAR, UINT32,   tach_gpio,         9) \
X(a, STATIC,   SINGULAR, UINT32,   source_id,        10) \
X(a, STATIC,   SINGULAR, UINT32,   curve_id,         11) \
X(a, STATIC,   SINGULAR, UINT32,   schedule_id,      12) \
X(a, STATIC,   SINGULAR, UINT32,   group_id,         13) \
X(a, STATIC,   SINGULAR, UENUM,    alarm,            14)
#define FanInfo_CALLBACK NULL
#define FanInfo_DEFAULT NULL

#define SourceInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   id,                1) \
X(a, STATIC,   SINGULAR, STRING,   name,              2) \
X(a, STATIC,   SINGULAR, UENUM,    type,              3) \
X(a, STATIC,   SINGULAR, UENUM,    status,            4) \
X(a, STATIC,   SINGULAR, FLOAT,    temp_c,            5) \
X(a, STATIC,   SINGULAR, UINT32,   gpio,              6) \
X(a, STATIC,   SINGULAR, UINT64,   ds18b20_rom_code,   7)
#define SourceInfo_CALLBACK NULL
#define SourceInfo_DEFAULT NULL

#define CurvePoint_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    temp_c,            1) \
X(a, STATIC,   SINGULAR, UINT32,   duty,              2)
#define CurvePoint_CALLBACK NULL
#define CurvePoint_DEFAULT NULL

#define CurveInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   id,                1) \
X(a, STATIC,   SINGULAR, STRING,   name,              2) \
X(a, STATIC,   REPEATED, MESSAGE,  points,            3)
#define CurveInfo_CALLBACK NULL
#define CurveInfo_DEFAULT NULL
#define CurveInfo_points_MSGTYPE CurvePoint

#define ScheduleInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   id,                1) \
X(a, STATIC,   SINGULAR, UINT32,   fan_id,            2) \
X(a, STATIC,   SINGULAR, UINT32,   duty,              3) \
X(a, STATIC,   SINGULAR, UINT32,   start_min,         4) \
X(a, STATIC,   SINGULAR, UINT32,   end_min,           5) \
X(a, STATIC,   SINGULAR, BOOL,     enabled,           6) \
X(a, STATIC,   SINGULAR, STRING,   name,              7)
#define ScheduleInfo_CALLBACK NULL
#define ScheduleInfo_DEFAULT NULL

#define WifiApRecord_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   ssid,              1) \
X(a, STATIC,   SINGULAR, INT32,    rssi,              2) \
X(a, STATIC,   SINGULAR, UINT32,   channel,           3) \
X(a, STATIC,   SINGULAR, UINT32,   authmode,          4)
#define WifiApRecord_CALLBACK NULL
#define WifiApRecord_DEFAULT NULL

#define SystemInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   version,           1) \
X(a, STATIC,   SINGULAR, UINT32,   uptime_s,          2) \
X(a, STATIC,   SINGULAR, UINT32,   heap_free,         3) \
X(a, STATIC,   SINGULAR, UINT32,   fan_count,         4) \
X(a, STATIC,   SINGULAR, UINT32,   source_count,      5) \
X(a, STATIC,   SINGULAR, UINT32,   curve_count,       6) \
X(a, STATIC,   SINGULAR, UINT32,   schedule_count,    7) \
X(a, STATIC,   SINGULAR, STRING,   hostname,          8)
#define SystemInfo_CALLBACK NULL
#define SystemInfo_DEFAULT NULL

#define WifiStatus_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     sta_connected,     1) \
X(a, STATIC,   SINGULAR, STRING,   sta_ip,            2) \
X(a, STATIC,   SINGULAR, STRING,   ap_ip,             3)
#define WifiStatus_CALLBACK NULL
#define WifiStatus_DEFAULT NULL

#define FanList_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  fans,              1)
#define FanList_CALLBACK NULL
#define FanList_DEFAULT NULL
#define FanList_fans_MSGTYPE FanInfo

#define FanCreateRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   pwm_gpio,          1) \
X(a, STATIC,   SINGULAR, UINT32,   tach_gpio,         2) \
X(a, STATIC,   SINGULAR, STRING,   name,              3)
#define FanCreateRequest_CALLBACK NULL
#define FanCreateRequest_DEFAULT NULL

#define FanUpdateRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   id,                1) \
X(a, STATIC,   OPTIONAL, UENUM,    mode,              2) \
X(a, STATIC,   OPTIONAL, UINT32,   duty,              3) \
X(a, STATIC,   OPTIONAL, UINT32,   source_id,         4) \
X(a, STATIC,   OPTIONAL, UINT32,   curve_id,          5) \
X(a, STATIC,   OPTIONAL, UINT32,   schedule_id,       6) \
X(a, STATIC,   OPTIONAL, UINT32,   group_id,          7) \
X(a, STATIC,   OPTIONAL, BOOL,     inverted,          8) \
X(a, STATIC,   OPTIONAL, BOOL,     enabled,           9) \
X(a, STATIC,   OPTIONAL, UINT32,   pwm_gpio,         10) \
X(a, STATIC,   OPTIONAL, UINT32,   tach_gpio,        11) \
X(a, STATIC,   OPTIONAL, STRING,   name,             12)
#define FanUpdateRequest_CALLBACK NULL
#define FanUpdateRequest_DEFAULT NULL

#define FanId_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   id,                1)
#define FanId_CALLBACK NULL
#define FanId_DEFAULT NULL

#define SourceList_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  sources,           1)
#define SourceList_CALLBACK NULL
#define SourceList_DEFAULT NULL
#define SourceList_sources_MSGTYPE SourceInfo

#define SourceCreateRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    type,              1) \
X(a, STATIC,   SINGULAR, STRING,   name,              2) \
X(a, STATIC,   SINGULAR, UINT32,   gpio,              3) \
X(a, STATIC,   SINGULAR, UINT64,   ds18b20_rom_code,   4)
#define SourceCreateRequest_CALLBACK NULL
#define SourceCreateRequest_DEFAULT NULL

#define SourceUpdateRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   id,                1) \
X(a, STATIC,   SINGULAR, STRING,   name,              2)
#define SourceUpdateRequest_CALLBACK NULL
#define SourceUpdateRequest_DEFAULT NULL

#define ManualTempRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   id,                1) \
X(a, STATIC,   SINGULAR, FLOAT,    temp_c,            2)
#define ManualTempRequest_CALLBACK NULL
#define ManualTempRequest_DEFAULT NULL

#define Ds18b20Device_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   index,             1) \
X(a, STATIC,   SINGULAR, UINT64,   rom_code,          2) \
X(a, STATIC,   SINGULAR, FLOAT,    temp_c,            3)
#define Ds18b20Device_CALLBACK NULL
#define Ds18b20Device_DEFAULT NULL

#define Ds18b20ScanResponse_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  devices,           1) \
X(a, STATIC,   SINGULAR, UINT32,   device_count,      2)
#define Ds18b20ScanResponse_CALLBACK pb_default_field_callback
#define Ds18b20ScanResponse_DEFAULT NULL
#define Ds18b20ScanResponse_devices_MSGTYPE Ds18b20Device

#define Ds18b20ConfigRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   gpio,              1)
#define Ds18b20ConfigRequest_CALLBACK NULL
#define Ds18b20ConfigRequest_DEFAULT NULL

#define CurveList_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  curves,            1)
#define CurveList_CALLBACK NULL
#define CurveList_DEFAULT NULL
#define CurveList_curves_MSGTYPE CurveInfo

#define CurveCreateRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   name,              1) \
X(a, STATIC,   REPEATED, MESSAGE,  points,            2)
#define CurveCreateRequest_CALLBACK NULL
#define CurveCreateRequest_DEFAULT NULL
#define CurveCreateRequest_points_MSGTYPE CurvePoint

#define CurveUpdateRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   id,                1) \
X(a, STATIC,   SINGULAR, STRING,   name,              2) \
X(a, STATIC,   REPEATED, MESSAGE,  points,            3)
#define CurveUpdateRequest_CALLBACK NULL
#define CurveUpdateRequest_DEFAULT NULL
#define CurveUpdateRequest_points_MSGTYPE CurvePoint

#define ScheduleList_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  schedules,         1)
#define ScheduleList_CALLBACK NULL
#define ScheduleList_DEFAULT NULL
#define ScheduleList_schedules_MSGTYPE ScheduleInfo

#define ScheduleCreateRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   fan_id,            1) \
X(a, STATIC,   SINGULAR, UINT32,   duty,              2) \
X(a, STATIC,   SINGULAR, UINT32,   start_min,         3) \
X(a, STATIC,   SINGULAR, UINT32,   end_min,           4) \
X(a, STATIC,   SINGULAR, BOOL,     enabled,           5) \
X(a, STATIC,   SINGULAR, STRING,   name,              6)
#define ScheduleCreateRequest_CALLBACK NULL
#define ScheduleCreateRequest_DEFAULT NULL

#define ScheduleUpdateRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   id,                1) \
X(a, STATIC,   OPTIONAL, UINT32,   fan_id,            2) \
X(a, STATIC,   OPTIONAL, UINT32,   duty,              3) \
X(a, STATIC,   OPTIONAL, UINT32,   start_min,         4) \
X(a, STATIC,   OPTIONAL, UINT32,   end_min,           5) \
X(a, STATIC,   OPTIONAL, BOOL,     enabled,           6) \
X(a, STATIC,   OPTIONAL, STRING,   name,              7)
#define ScheduleUpdateRequest_CALLBACK NULL
#define ScheduleUpdateRequest_DEFAULT NULL

#define WifiScanResult_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  aps,               1)
#define WifiScanResult_CALLBACK NULL
#define WifiScanResult_DEFAULT NULL
#define WifiScanResult_aps_MSGTYPE WifiApRecord

#define WifiConnectRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   ssid,              1) \
X(a, STATIC,   SINGULAR, STRING,   password,          2)
#define WifiConnectRequest_CALLBACK NULL
#define WifiConnectRequest_DEFAULT NULL

#define HostnameRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   hostname,          1)
#define HostnameRequest_CALLBACK NULL
#define HostnameRequest_DEFAULT NULL

#define ConfigFile_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   version,           1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  fans,              2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  sources,           3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  curves,            4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  schedules,         5)
#define ConfigFile_CALLBACK NULL
#define ConfigFile_DEFAULT NULL
#define ConfigFile_fans_MSGTYPE FanList
#define ConfigFile_sources_MSGTYPE SourceList
#define ConfigFile_curves_MSGTYPE CurveList
#define ConfigFile_schedules_MSGTYPE ScheduleList

#define Empty_FIELDLIST(X, a) \

#define Empty_CALLBACK NULL
#define Empty_DEFAULT NULL

#define StatusResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     ok,                1) \
X(a, STATIC,   SINGULAR, UINT32,   error_code,        2) \
X(a, STATIC,   SINGULAR, STRING,   error_msg,         3)
#define StatusResponse_CALLBACK NULL
#define StatusResponse_DEFAULT NULL

extern const pb_msgdesc_t FanInfo_msg;
extern const pb_msgdesc_t SourceInfo_msg;
extern const pb_msgdesc_t CurvePoint_msg;
extern const pb_msgdesc_t CurveInfo_msg;
extern const pb_msgdesc_t ScheduleInfo_msg;
extern const pb_msgdesc_t WifiApRecord_msg;
extern const pb_msgdesc_t SystemInfo_msg;
extern const pb_msgdesc_t WifiStatus_msg;
extern const pb_msgdesc_t FanList_msg;
extern const pb_msgdesc_t FanCreateRequest_msg;
extern const pb_msgdesc_t FanUpdateRequest_msg;
extern const pb_msgdesc_t FanId_msg;
extern const pb_msgdesc_t SourceList_msg;
extern const pb_msgdesc_t SourceCreateRequest_msg;
extern const pb_msgdesc_t SourceUpdateRequest_msg;
extern const pb_msgdesc_t ManualTempRequest_msg;
extern const pb_msgdesc_t Ds18b20Device_msg;
extern const pb_msgdesc_t Ds18b20ScanResponse_msg;
extern const pb_msgdesc_t Ds18b20ConfigRequest_msg;
extern const pb_msgdesc_t CurveList_msg;
extern const pb_msgdesc_t CurveCreateRequest_msg;
extern const pb_msgdesc_t CurveUpdateRequest_msg;
extern const pb_msgdesc_t ScheduleList_msg;
extern const pb_msgdesc_t ScheduleCreateRequest_msg;
extern const pb_msgdesc_t ScheduleUpdateRequest_msg;
extern const pb_msgdesc_t WifiScanResult_msg;
extern const pb_msgdesc_t WifiConnectRequest_msg;
extern const pb_msgdesc_t HostnameRequest_msg;
extern const pb_msgdesc_t ConfigFile_msg;
extern const pb_msgdesc_t Empty_msg;
extern const pb_msgdesc_t StatusResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define FanInfo_fields &FanInfo_msg
#define SourceInfo_fields &SourceInfo_msg
#define CurvePoint_fields &CurvePoint_msg
#define CurveInfo_fields &CurveInfo_msg
#define ScheduleInfo_fields &ScheduleInfo_msg
#define WifiApRecord_fields &WifiApRecord_msg
#define SystemInfo_fields &SystemInfo_msg
#define WifiStatus_fields &WifiStatus_msg
#define FanList_fields &FanList_msg
#define FanCreateRequest_fields &FanCreateRequest_msg
#define FanUpdateRequest_fields &FanUpdateRequest_msg
#define FanId_fields &FanId_msg
#define SourceList_fields &SourceList_msg
#define SourceCreateRequest_fields &SourceCreateRequest_msg
#define SourceUpdateRequest_fields &SourceUpdateRequest_msg
#define ManualTempRequest_fields &ManualTempRequest_msg
#define Ds18b20Device_fields &Ds18b20Device_msg
#define Ds18b20ScanResponse_fields &Ds18b20ScanResponse_msg
#define Ds18b20ConfigRequest_fields &Ds18b20ConfigRequest_msg
#define CurveList_fields &CurveList_msg
#define CurveCreateRequest_fields &CurveCreateRequest_msg
#define CurveUpdateRequest_fields &CurveUpdateRequest_msg
#define ScheduleList_fields &ScheduleList_msg
#define ScheduleCreateRequest_fields &ScheduleCreateRequest_msg
#define ScheduleUpdateRequest_fields &ScheduleUpdateRequest_msg
#define WifiScanResult_fields &WifiScanResult_msg
#define WifiConnectRequest_fields &WifiConnectRequest_msg
#define HostnameRequest_fields &HostnameRequest_msg
#define ConfigFile_fields &ConfigFile_msg
#define Empty_fields &Empty_msg
#define StatusResponse_fields &StatusResponse_msg

/* Maximum encoded size of messages (where known) */
/* Ds18b20ScanResponse_size depends on runtime parameters */
#define ConfigFile_size                          3981
#define CurveCreateRequest_size                  147
#define CurveInfo_size                           153
#define CurveList_size                           2496
#define CurvePoint_size                          11
#define CurveUpdateRequest_size                  153
#define Ds18b20ConfigRequest_size                6
#define Ds18b20Device_size                       22
#define ESPFM_PB_H_MAX_SIZE                      ConfigFile_size
#define Empty_size                               0
#define FanCreateRequest_size                    29
#define FanId_size                               6
#define FanInfo_size                             79
#define FanList_size                             648
#define FanUpdateRequest_size                    71
#define HostnameRequest_size                     65
#define ManualTempRequest_size                   11
#define ScheduleCreateRequest_size               43
#define ScheduleInfo_size                        49
#define ScheduleList_size                        408
#define ScheduleUpdateRequest_size               49
#define SourceCreateRequest_size                 36
#define SourceInfo_size                          49
#define SourceList_size                          408
#define SourceUpdateRequest_size                 23
#define StatusResponse_size                      73
#define SystemInfo_size                          114
#define WifiApRecord_size                        57
#define WifiConnectRequest_size                  99
#define WifiScanResult_size                      944
#define WifiStatus_size                          36

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
