# setup_v3_libs.ps1 — Download real nanopb + microcoap and wire into ESPFM v3
$ErrorActionPreference = "Stop"
$base = "C:\Users\KaoTD\espfm-core"

Write-Host "=== Downloading nanopb core from GitHub ==="
$nanopb = "$base\components\nanopb"
$url = "https://raw.githubusercontent.com/nanopb/nanopb/master"
Invoke-WebRequest -Uri "$url/pb.h" -OutFile "$nanopb\include\pb.h"
Invoke-WebRequest -Uri "$url/pb_encode.h" -OutFile "$nanopb\include\pb_encode.h"
Invoke-WebRequest -Uri "$url/pb_decode.h" -OutFile "$nanopb\include\pb_decode.h"
Invoke-WebRequest -Uri "$url/pb_common.c" -OutFile "$nanopb\pb_common.c"
Invoke-WebRequest -Uri "$url/pb_encode.c" -OutFile "$nanopb\pb_encode.c"
Invoke-WebRequest -Uri "$url/pb_decode.c" -OutFile "$nanopb\pb_decode.c"
Write-Host "  nanopb: OK"

Write-Host "=== Downloading microcoap from GitHub ==="
$mcoap = "$base\components\microcoap"
Invoke-WebRequest -Uri "https://raw.githubusercontent.com/1248/microcoap/master/coap.h" -OutFile "$mcoap\coap.h"
Invoke-WebRequest -Uri "https://raw.githubusercontent.com/1248/microcoap/master/coap.c" -OutFile "$mcoap\coap.c"
Write-Host "  microcoap: OK"

Write-Host "=== Components ready ==="
Write-Host "nanopb:  $nanopb"
Write-Host "microcoap: $mcoap"
Write-Host ""
Write-Host "Next: idf.py build"
